version: "3.9"

services:
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  api:
    container_name: api_container
    build: .
    ports:
      - 8080:8080
    environment:
      MONGO_URI: ${MONGO_URI}
      YOUTUBE_API_KEYS: ${YOUTUBE_API_KEYS}
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
